#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running type checks..."
# Backend Type Check
echo "Checking Backend..."
(cd backend && npx tsc --noEmit)

# Frontend Type Check
echo "Checking Frontend..."
(cd frontend && npx tsc --noEmit)
